=== tiberiu-biking/around-the-world-boot/jaxb/target/classes/import.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="xmlSource">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="markers" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="note"/>
                            <xs:element type="xs:byte" name="latitude"/>
                            <xs:element type="xs:byte" name="longitude"/>
                            <xs:element type="xs:date" name="date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tiberiu-biking/around-the-world-boot/domain/src/main/resources/import.xml
<?xml version="1.0" encoding="UTF-8"  ?>

<xmlSource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="import.xsd">

    <markers>
        <name>M1</name>
        <note>Note1</note>
        <latitude>1</latitude>
        <longitude>2</longitude>
        <date>2014-09-07</date>
    </markers>

    <markers>
        <name>M1</name>
        <note>Note1</note>
        <latitude>1</latitude>
        <longitude>2</longitude>
        <date>2014-09-07</date>
    </markers>


</xmlSource>
